name: Security Trivy dependency check

on:
  workflow_call:
    inputs:
      channel_id:
        description: 'The slack channel ID to send a message on failure. If this is not provided then no message is sent.'
        required: false
        default: 'NO_SLACK'
        type: string
      subproject:
        description: 'For gradle multi module projects, leave blank for single module projects'
        required: false
        default: ''
        type: string
      ignore_unfixed:
        description: 'Asserts the Trivy scan to ignore vulnerabilities that have no current fix'
        required: false
        default: true
        type: boolean
      severity:
        description: 'Customisable severity levels'
        required: false
        default: 'HIGH,CRITICAL'
        type: string
      limit_severities_for_sarif:
        description: 'only includes severities as defined in the sarif file'
        required: false
        default: true
        type: boolean
      slack_include_summary:
        description: 'boolean to include a summary of vulnerabilities in the Slack message'
        required: false
        default: true
        type: boolean
      scan_type:
        description: 'A scan type to use - either image (default) or fs'
        required: false
        default: 'image' # As per the Trivy inputs list https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#inputs
        type: string      
      scanners:
        description: 'A comma-separated list of scanners to use to scan - used for filesystem scans'
        required: false
        default: 'misconfig,vuln,secret'
        type: string
      location:
        description: 'A location for IaC scans to take place'
        required: false
        default: '.'
        type: string        
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: 'Slack bot token'
        required: false

permissions:
  contents: read
  security-events: write

jobs:
  security-trivy-check:
    name: Security trivy dependency check
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      packages: read
      security-events: write
      contents: read
      actions: read
    steps:
    - uses: actions/checkout@v6
    
    - name: Run Trivy Security Scan
      id: trivy-scan
      uses: ministryofjustice/hmpps-github-actions/.github/actions/trivy-scan@v2 # WORKFLOW_VERSION
      with:
        subproject: ${{ inputs.subproject }}
        severity: ${{ inputs.severity }}
        scan_type: ${{ inputs.scan_type }}
        scanners: ${{ inputs.scanners }}
        location: ${{ inputs.location }}
        ignore_unfixed: ${{ inputs.ignore_unfixed }}
        limit_severities_for_sarif: ${{ inputs.limit_severities_for_sarif }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trivy slack notification
      uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_codescan_notification@v2 # WORKFLOW_VERSION
      if: (failure() || steps.trivy-scan.outcome == 'failure') && inputs.channel_id != 'NO_SLACK'
      with:
        title: "Trivy"
        warningOnly: ${{ steps.trivy-scan.outputs.sarif_upload_outcome == 'success' }}
        channel_id: ${{ inputs.channel_id}}
        SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
        subproject: ${{ inputs.subproject }}
        summary: ${{ inputs.slack_include_summary && steps.trivy-scan.outputs.summary || '' }}
